### ISSUE TITLE
How do I initialize Factual driver within an initializer?

### ISSUE THREAD

**Issue by aswinramakrish** [Factual/factual-ruby-driver#33]
This could be a silly question, but I wanted to know if I can initialize Factual driver within an initializer, instead of having the API key and secret everywhere I use Factual driver (in controllers, helpers etc.)

**Comment by dirtyvagabond** [comment]
I believe the currently recommended approach of initializing a Factual handle and then passing that handle around your app as necessary, basically solves this? E.g.:

```ruby
# make this handle accessible from elsewhere in your app:
factual = Factual.new("YOUR_KEY", "YOUR_SECRET")

# ... later, somewhere else in your app:
factual.table("places-us").search("century city mall").rows
```

Please see the main project README for further docs. https://github.com/Factual/factual-ruby-driver/blob/master/README.md

**Comment by aswinramakrish** [comment]
Can I initialize the handle in an initializer and pass it to my controllers and helpers?

**Comment by dirtyvagabond** [comment]
Yes! Have fun and let us know how it goes!  :+1:
